### ISSUE TITLE
Scheduler: List Index out of range

### ISSUE THREAD

**Issue by clfromhell** [seiferta/eMonitor#47]
Seit einiger Zeit reagiert die Verzeichnisüberwachung nicht mehr und beim Speichern eines neuen Überwachungsintervalls erscheint nur ein Error 500.
Folgenden Trace konnte ich der eMonitor-error.log entnehmen:
`2016-08-25 15:41:08,788 - ERROR - eMonitor - Exception on /admin/settings [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/eMonitor/emonitor/decorators.py", line 21, in decorated_function
    return f(*args, **kwargs)
  File "/root/eMonitor/emonitor/admin/admin.py", line 94, in adminContent
    return current_mod.getAdminContent(modules=admin.modules, current_mod=current_mod, user=User.getUsers(login.current_user.get_id() or -1), app_name=current_app.config.get('PROJECT'), app_version=current_app.config.get('APP_VERSION'),$
  File "/root/eMonitor/emonitor/modules/settings/__init__.py", line 77, in getAdminContent
    return getAdminContent(self, **params)
  File "/root/eMonitor/emonitor/modules/settings/content_admin.py", line 153, in getAdminContent
    _jobserver = scheduler.get_jobs('observerinterval')[0]
IndexError: list index out of range
`

**Comment by seiferta** [comment]
Das Problem besteht seit der Umstellung auf eine zusätzliche Möglichkeit der Verzeichnisüberwachung per Python Modul "watchdog". (> pip install watchdog)
Wenn das Modul installiert ist, funktioniert die Verzeichnisüberwachung wieder, wie gewohnt. Die gelistete Fehlermeldung wird aber noch weiter auftauchen, allerdings ohne Auswirkungen auf den Auswertungsbetrieb.
