### ISSUE TITLE
"Sqlite error: Database is locked"  um 12 und 0 Uhr

### ISSUE THREAD

**Issue by clfromhell** [seiferta/eMonitor#60]
Hallo allerseits,

Ich erhalte sporadisch gegen 0 und 12 Uhr jeweils 2 "Database is locked"-Fehler von sqlite, was dann auch einen Absturz vom eMonitor erzeugt. Die Datenbank wird jedoch von niemanden über sqlite geöffnet, wenn dieser Fehler auftritt.
Ich erhalte folgende Traces:
`2017-01-20 00:00:34,355 - ERROR - eMonitor - Exception on /admin/settings/communication [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/emonitor/emonitor/decorators.py", line 19, in decorated_function
    if (not current_user.is_authenticated) or current_user.level != 1:
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 338, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 297, in _get_current_object
    return self.__local()
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 26, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 302, in _get_user
    current_app.login_manager._load_user()
  File "/usr/local/lib/python2.7/dist-packages/flask_login/login_manager.py", line 317, in _load_user
    return self.reload_user()
  File "/usr/local/lib/python2.7/dist-packages/flask_login/login_manager.py", line 279, in reload_user
    user = self.user_callback(user_id)
  File "/emonitor/emonitor/app.py", line 187, in load_user
    return User.getUsers(userid=id)
  File "/emonitor/emonitor/user.py", line 82, in getUsers
    if user.first():
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2695, in first
    ret = list(self[0:1])
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2487, in __getitem__
    return list(res)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2795, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2818, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 462, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (sqlite3.OperationalError) database is locked [SQL: u'SELECT users.password AS users_password, users.id AS users_id, users.username AS users_username, users.email AS users_email, users.level AS users_level, users.right$

2017-01-20 00:00:34,450 - ERROR - cherrypy.error - [20/Jan/2017:00:00:34] ENGINE OperationalError('(sqlite3.OperationalError) database is locked',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/wsgiserver/__init__.py", line 1408, in communicate
    req.respond()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/wsgiserver/__init__.py", line 862, in respond
    self.server.gateway(self).respond()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/wsgiserver/__init__.py", line 2333, in respond
    response = self.req.server.wsgi_app(self.env, self.start_response)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cptree.py", line 287, in __call__
    return app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1574, in handle_exception
    return handler(e)
  File "/emonitor/emonitor/app.py", line 312, in server_error_page
    return render_template("errors500.html"), 500
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 132, in render_template
    ctx.app.update_template_context(context)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 765, in update_template_context
    context.update(func())
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 335, in _user_context_processor
    return dict(current_user=_get_user())
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 302, in _get_user
    current_app.login_manager._load_user()
  File "/usr/local/lib/python2.7/dist-packages/flask_login/login_manager.py", line 317, in _load_user
    return self.reload_user()
  File "/usr/local/lib/python2.7/dist-packages/flask_login/login_manager.py", line 279, in reload_user
    user = self.user_callback(user_id)
  File "/emonitor/emonitor/app.py", line 187, in load_user
    return User.getUsers(userid=id)
  File "/emonitor/emonitor/user.py", line 82, in getUsers
 if user.first():
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2695, in first
    ret = list(self[0:1])
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2487, in __getitem__
    return list(res)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2795, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2818, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 462, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (sqlite3.OperationalError) database is locked [SQL: u'SELECT users.password AS users_password, users.id AS users_id, users.username AS users_username, users.email AS users_email, users.level AS users_level, users.right$`

Woran könnte dieses Problem liegen?

**Comment by seiferta** [comment]
Diesen Effekt konnte ich auch schon bei SQLite beobachten, leider ohne einen Anhaltspunkt, was genau schuld ist.
Es kann eigentlich nur an einer "hängengebliebenen" Abfrage liegen, habe aber im Vorfeld keine Fehler in den Logs gefunden.
Hatte dann auf MySql gewechselt, seitdem gibt es keine Probleme mehr.

**Comment by seiferta** [comment]
im Bin-Verzeichnis liegt ein Konvertierungs-Script: convert_sqlite_to_mysql.py
Habe es selber allerdings mit der aktuellen Version nicht getestet, das hat mir "unsere" Datenbank seinerzeit korrekt konvertiert.

**Comment by clfromhell** [comment]
Das Konvertieren der Datenbank hat nun mit der MySQL Workbench funktioniert. Nun habe ich aber das Problem, dass mir auf der Startseite das Alarm-Modul nicht mehr angezeigt wird und mir SQLAlchemy einen Fehler wirft.
Folgenden Trace konnte ich entnehmen:
`OperationalError: (_mysql_exceptions.OperationalError) (1055, "Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'emonitor.alarms.timestamp' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by") [SQL: u'SELECT alarms.state AS alarms_state, count(alarms.id) AS count_1 \nFROM alarms \nWHERE alarms.timestamp > %s GROUP BY alarms.state ORDER BY alarms.timestamp DESC'] [parameters: (datetime.datetime(2017, 1, 28, 10, 54, 27, 209233),)]`

**Comment by seiferta** [comment]
in deinem Ausschnitt-Log wird leider nicht gesagt, an welcher Stelle genau der Fehler fliegt. So lässt sich das leider nicht nachvollziehen.

**Comment by clfromhell** [comment]
Der Fehler tritt bei verschiedenen Modulen jeweils bei einem "Group by"-Sql Aufruf auf. Es lässt sich umgehen, wenn am Ende nach dem zu gruppierenden Wert und zusätzlich nach der Feld-ID gruppiert wird.

**Comment by clfromhell** [comment]
Mir ist jedoch gerade aufgefallen, dass dieses Workaround dann die Anzeige entweder verfälscht (Bei der Ausrückeordnung) oder die Anzeige leer ist (Modul Alarme im Eingabeoberfläche).
Hier ein voller Trace aus der eMonitor.log:
`2017-02-05 16:31:46,234 - ERROR - eMonitor - Exception on /alarms [GET]
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
File "/emonitor/emonitor/frontend/frontend.py", line 57, in frontendContent
    return current_mod.getFrontendContent()
File "/emonitor/emonitor/modules/alarms/__init__.py", line 215, in getFrontendContent
    return getFrontendContent(**params)
File "/emonitor/emonitor/modules/alarms/content_frontend.py", line 172, in getFrontendContent
    for s, c in Alarm.getAlarmCount(days=int(session['alarmfilter'])):  # s=state, c=count(ids of state)
File "/emonitor/emonitor/modules/alarms/alarm.py", line 263, in getAlarmCount
    return db.get(Alarm.state, count(Alarm.id)).filter(Alarm.timestamp > (datetime.datetime.now() - datetime.timedelta(days=days))).order_by(Alarm.timestamp.desc()).group_by(Alarm.state).all()
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2643, in all
    return list(self)
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2795, in __iter__
    return self._execute_and_instances(context)
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2818, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
    exc_info
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 462, in do_execute
    cursor.execute(statement, parameters)
File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 226, in execute
    self.errorhandler(self, exc, value)
File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorvalue
OperationalError: (_mysql_exceptions.OperationalError) (1055, "Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'emonitor.alarms.timestamp' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by") [SQL: u'SELECT alarms.state AS alarms_state, count(alarms.id) AS count_1 \nFROM alarms \nWHERE alarms.timestamp > %s GROUP BY alarms.state ORDER BY alarms.timestamp DESC'] [parameters: (datetime.datetime(2017, 1, 28, 10, 54, 27, 209233),)]`

**Comment by seiferta** [comment]
Das Problem liegt an einer anderen Stelle (z.B. stackoverflow erklärt)

in MySQL kann man den "sql_mode" setzen. Der war in älteren Versionen toleranter und steht anscheinend in der aktuellen Version auf "only_full_group_by".
Habe gerade mal bei mir nachgesehen, da steht das auf dem Wert: 

`'sql_mode', 'STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'`

damit funktioniert es. Kann man auslesen über
`SHOW VARIABLES;` in der MySQL Konsole

**Comment by clfromhell** [comment]
So funktioniert es, danke!

Es ist nur wichtig, dass man den sql_mode nicht in der MySQL-Konsole setzt, sondern direkt in der my.cnf bzw. my.ini, jeweils im Abschnitt [mysqld].
