### ISSUE TITLE
Drucken bei Alarmeingang schlägt fehl

### ISSUE THREAD

**Issue by seiferta** [seiferta/eMonitor#63]
ERROR:emonitor.events:handleEvent alarm_added.ILS_Erding: Traceback (most recent call last):
  File "C:\emonitor\emonitor\emonitor\events.py", line 95, in run
    handler.handle(self.kwargs)
  File "C:\emonitor\emonitor\emonitor\events.py", line 29, in handle
    args.update(handler[1](self.name, **args))
  File "C:\emonitor\emonitor\emonitor\modules\printers\printers.py", line 124, in handleEvent
    _printer.doPrint(**dict(kwargs))
  File "C:\emonitor\emonitor\emonitor\modules\printers\printers.py", line 90, in doPrint
    tmpfile.write(Module.getPdf(params['object'].getExportData('.html', **_params)))
  File "C:\emonitor\emonitor\emonitor\modules\alarms\alarm.py", line 406, in getExportData
    fname = "{}/{}".format(current_app.config.get('PATH_DONE'), alarm.get('filename'))
  File "C:\Python27\lib\site-packages\werkzeug\local.py", line 338, in __getattr__
    return getattr(self._get_current_object(), name)
  File "C:\Python27\lib\site-packages\werkzeug\local.py", line 297, in _get_current_object
    return self.__local()
  File "C:\Python27\lib\site-packages\flask\globals.py", line 51, in _find_app
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.

**Comment by seiferta** [comment]
Traceback (most recent call last):
  File "D:\dev\python\2.7.10\Lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "D:\daten\python\eMonitor\emonitor\events.py", line 95, in run
    handler.handle(self.kwargs)
  File "D:\daten\python\eMonitor\emonitor\events.py", line 29, in handle
    args.update(handler[1](self.name, **args))
  File "D:\daten\python\eMonitor\emonitor\modules\printers\printers.py", line 127, in handleEvent
    _printer.doPrint(**dict(kwargs))
  File "D:\daten\python\eMonitor\emonitor\modules\printers\printers.py", line 93, in doPrint
    tmpfile.write(Module.getPdf(params['object'].getExportData('.html', **_params)))
  File "D:\daten\python\eMonitor\emonitor\modules\alarms\alarm.py", line 427, in getExportData
    return render_template('print.{}.html'.format(params['style']), **params)
  File "D:\dev\python\virtualenv\emonitor\lib\site-packages\flask\templating.py", line 132, in render_template
    ctx.app.update_template_context(context)
AttributeError: 'NoneType' object has no attribute 'app'
