### ISSUE TITLE
Straßen von OpenStreetMap laden - AttributeError: 'NoneType' object has no attribute 'getMapBox'

### ISSUE THREAD

**Issue by joachimbk** [seiferta/eMonitor#75]
Hallo,

egal ob ich im VirtualBox Image oder in meiner Installation die Straßen von OpenStreetMap laden möchte, bekomme ich immer den unten aufgeführten Fehler im Logfile.

Städte/Orte konnte erfolgreich geladen werden, nur die Straßenliste nicht.
Bin gerne bereit für gemeinsame TeamViewer Session um den Fehler zu suchen. 

Viele Grüße
Joachim

ERROR:cherrypy.error:[23/Sep/2017:13:30:42] ENGINE AttributeError("'NoneType' object has no attribute 'getMapBox'",)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/wsgiserver/__init__.py", line 1408, in communicate
    req.respond()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/wsgiserver/__init__.py", line 862, in respond
    self.server.gateway(self).respond()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/wsgiserver/__init__.py", line 2333, in respond
    response = self.req.server.wsgi_app(self.env, self.start_response)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cptree.py", line 287, in __call__
    return app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/emonitor/emonitor/admin/admin.py", line 110, in adminData
    result = current_mod.getAdminData()
  File "/opt/emonitor/emonitor/modules/streets/__init__.py", line 93, in getAdminData
    return getAdminData(self)
  File "/opt/emonitor/emonitor/modules/streets/content_admin.py", line 167, in getAdminData
    return loadStreetsFromOsm(City.getCities(id=request.args.get('cityid')))
  File "/opt/emonitor/emonitor/modules/streets/street_utils.py", line 62, in loadStreetsFromOsm
    map_details = Map.getDefaultMap().getMapBox(tilepath=current_app.config.get('PATH_TILES'))
AttributeError: 'NoneType' object has no attribute 'getMapBox'

**Comment by seiferta** [comment]
Das sieht nach einem Problem in der Konfiguration der Stadt/Ort aus in Kombination mit einer unvollständigen Definition der Karte.

Bräuchte mal die Datenbank oder einen Dump, um das zu kontrollieren.

**Comment by joachimbk** [comment]
Hallo, 

emonitor.db im Anhang. Vielen Dank schonmal.
[emonitor.db.zip](https://github.com/seiferta/eMonitor/files/1341623/emonitor.db.zip)

**Comment by seiferta** [comment]
Hier mal die Datei mit korrigierter Karte und Straßen für den Hauptort.

[emonitor.zip](https://github.com/seiferta/eMonitor/files/1419153/emonitor.zip)

**Comment by jonny1213** [comment]
Was und wie muss denn die emonitor.db geändert werden?
Ich bekomme auch diesen Fehler.
[emonitor.zip](https://github.com/seiferta/eMonitor/files/1622521/emonitor.zip)

**Comment by seiferta** [comment]
Im Admin-Bereich muss im Menüpunkt "Straßenkarte" eine Karte als "Standardkarte" definiert worden sein, sonst klappt der Download nicht.
am sinnvollsten ist das sicherlich für die OSM-Karte.
