### ISSUE TITLE
Configuration Fax

### ISSUE THREAD

**Issue by Fritz160** [seiferta/eMonitor#78]
Hi, ich versuche seit längeren jetzt schon Emonitor einzurichten. Soweit funktioniert eigentlich alles außer die Faxverarbeitung.
Könnte mir jemand seien Configurationen von Eventhandling  zur Verfügung stellen, damit ich es auf diesen Weg einmal testen kann?

Vielen Dank für eure Hilfe!
Fritz

**Comment by jonny1213** [comment]
![event](https://user-images.githubusercontent.com/17815379/36499276-0e556504-1741-11e8-9a8e-7a6575149f67.PNG)

**Comment by Fritz160** [comment]
Vielen Dank @jonny1213 für die so schnelle Antwort. Wollte es testen mit der Testverarbeitung mit Beispiel-Datei. So weit erstellt er ein fertig ausgelesenes Fax in temp.txt, aber dann zeigt er ewig " Aktionen werden ausgeführt" an und wird leider nicht fertig. Hattest Du dies zufällig auch schon?

**Comment by sambandi** [comment]
Hol dir am Besten das lauffähige VirtualBox Image und orientiere dich an dessen Konfiguration: 
http://seiferta.github.io/eMonitor/virtualbox-image

**Comment by seiferta** [comment]
Wenn er ewig nicht "fertig" wird, dann kann es daran liegen, dass im Hintergrund ein Problem aufgetreten ist, dass der Prozess hängen bleibt.
Gerade diese Prozesssteuerung ist relativ komplex und es kommt immer drauf an, wie gut die Qualität des erkannten Textes ist, ob der Prozess sauber durchläuft.

Vielleicht hilft es, bei den einzelnen Schritten der Testverarbeitung mal zu kontrollieren, was für ein Text denn wirklich aus dem Fax erkannt wurde. Wenn der zu viele falsche Zeichen beinhaltet, dann ist das der erste Ansatzpunkt.

**Comment by Fritz160** [comment]
Die OCR Erkennung funktioniert tadellos. Der erkannte Text hat keinen Fehler und auch das Layout stimmt damit überein. Bei manuellen hinzufügen einer Datei bekomme ich folgenden Fehler in der Konsole:

DEBUG:emonitor.events:  > arguments {'incomepath': './data/income/', 'filename': 'HP0001.jpg'}
INFO:emonitor.events:try handleEvent file_added
INFO:emonitor.observer:file_added: ./data/income/HP0001.jpg
DEBUG:emonitor.signals:send signal alarm.error with: {'text': '', 'message': 'alarms.errorincreation'}
INFO:emonitor.signals:send signal alarm.error
INFO:emonitor.events:eventDone file_added
DEBUG:emonitor.signals:send signal monitorserver.clientsearchstart with: {'clients': []}
INFO:emonitor.signals:send signal monitorserver.clientsearchstart
Exception in thread Thread-47:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/ff/Documents/seiferta-eMonitor-d7fe8e2/emonitor/monitorserver.py", line 212, in run
    self.sock.sendto(message, (self.MCAST_ADDR, self.MCAST_PORT))
error: [Errno 101] Network is unreachable

DEBUG:PIL.PngImagePlugin:STREAM IHDR 16 13
DEBUG:PIL.PngImagePlugin:STREAM iCCP 41 2340
DEBUG:PIL.PngImagePlugin:iCCP profile name icc
DEBUG:PIL.PngImagePlugin:Compression method 0
DEBUG:PIL.PngImagePlugin:STREAM cHRM 2393 32
DEBUG:PIL.PngImagePlugin:cHRM 2393 32 (unknown)
DEBUG:PIL.PngImagePlugin:STREAM bKGD 2437 2
DEBUG:PIL.PngImagePlugin:bKGD 2437 2 (unknown)
DEBUG:PIL.PngImagePlugin:STREAM pHYs 2451 9
DEBUG:PIL.PngImagePlugin:STREAM tIME 2472 7
DEBUG:PIL.PngImagePlugin:tIME 2472 7 (unknown)
DEBUG:PIL.PngImagePlugin:STREAM IDAT 2491 18376
Tesseract Open Source OCR Engine v3.04.01 with Leptonica
DEBUG:emonitor.signals:send signal monitorserver.clientsearchstart with: {'clients': []}
INFO:emonitor.signals:send signal monitorserver.clientsearchstart
Exception in thread Thread-48:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/ff/Documents/seiferta-eMonitor-d7fe8e2/emonitor/monitorserver.py", line 212, in run
    self.sock.sendto(message, (self.MCAST_ADDR, self.MCAST_PORT))
error: [Errno 101] Network is unreachable

**Comment by Fritz160** [comment]
Wenn ich die Testverarbeitung starte, liest er das Alarmfax richtig aus und speichert es richtig und vollständig richtig erkannt ab. Dann bekomme ich jedoch diesen Fehler:

_Verarbeitungs-Protokoll
replace: replace done in 0.00150513648987 sec.

Fehler: Notwendiger Parameter 'out.fields' für Event-Handler 'Alarmerstellung' wurde nicht gefunden/konfiguriert.

Parameter 'out.fields'nicht gefunden_

Was stimmt bei mir noch nicht? Vielen Dank!!

**Comment by RettungsTim** [comment]
Ich habe den Fehler mit out.fields auch. Wurde da der Fehler gefunden? Ich komme da nicht weiter.
