### ISSUE TITLE
Fehler bei Alarmerstellung

### ISSUE THREAD

**Issue by Fritz160** [seiferta/eMonitor#83]
Hallo,

Bei der Testverarbeitung werden alle Variablen richtig zugeordnet. Nur unter Alarm-Object zeigt er nichts an? Ist das schlimm?
Wenn man aber in den ./income Ordner ein file legt, wird dieses richtig verarbeitet, jedoch zeigt er einen Fehler bei der Alarmerstellung an und in der Konsole steht:
INFO:emonitor.signals:send signal alarm.error

Wie kann ich das Problem näher einkreisen?

Vielen Dank,
Fritz

**Comment by bhallinger** [comment]
Hallo,
das Gleiche bei mir. leider komme ich mit den Ausgaben im Log nicht weiter....

Hier mein Log.


2018-05-02 10:39:16,946 - ERROR - emonitor.modules.alarms.faxchecker.GENERIC (regex) - field(s) empty or eval error: person,addresspart,crossing,object,alarmplan,material

2018-05-02 10:39:16,993 - ERROR - emonitor.events - handleEvent file_added: Traceback (most recent call last):
  File "/srv/emonitor/emonitor/events.py", line 95, in run
    handler.handle(self.kwargs)
  File "/srv/emonitor/emonitor/events.py", line 29, in handle
    args.update(handler[1](self.name, **args))
  File "/srv/emonitor/emonitor/modules/alarms/alarm.py", line 823, in handleEvent
    signal.send('alarm', 'error', message='alarms.errorincreation', text=kwargs.get('text', ''))
  File "/srv/emonitor/emonitor/signals.py", line 31, in send
    self.signals['{}.{}'.format(classname, option)].send(str(payload))
  File "/usr/local/lib/python2.7/dist-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/srv/emonitor/emonitor/modules/alarms/__init__.py", line 246, in handleAlarmErrors
    SocketHandler.send_message(sender, **extra)
  File "/srv/emonitor/emonitor/socketserver.py", line 24, in send_message
    subscriber.send(payload)
  File "/usr/local/lib/python2.7/dist-packages/ws4py/websocket.py", line 297, in send
    self._write(m)
  File "/usr/local/lib/python2.7/dist-packages/ws4py/websocket.py", line 279, in _write
    self.sock.sendall(b)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 32] Broken pipe


2018-05-02 10:39:17,004 - ERROR - emonitor.modules.alarms.faxchecker.GENERIC (regex) - field(s) empty or eval error: person,addresspart,crossing,object,alarmplan,material

2018-05-02 10:39:17,018 - ERROR - emonitor.modules.alarms.faxchecker.GENERIC (regex) - field(s) empty or eval error: person,addresspart,crossing,object,alarmplan,material

2018-05-02 10:39:17,048 - ERROR - emonitor.events - handleEvent file_added: Traceback (most recent call last):
  File "/srv/emonitor/emonitor/events.py", line 95, in run
    handler.handle(self.kwargs)
  File "/srv/emonitor/emonitor/events.py", line 29, in handle
    args.update(handler[1](self.name, **args))
  File "/srv/emonitor/emonitor/modules/alarms/alarm.py", line 823, in handleEvent
    signal.send('alarm', 'error', message='alarms.errorincreation', text=kwargs.get('text', ''))
  File "/srv/emonitor/emonitor/signals.py", line 31, in send
    self.signals['{}.{}'.format(classname, option)].send(str(payload))
  File "/usr/local/lib/python2.7/dist-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/srv/emonitor/emonitor/modules/alarms/__init__.py", line 246, in handleAlarmErrors
    SocketHandler.send_message(sender, **extra)
  File "/srv/emonitor/emonitor/socketserver.py", line 24, in send_message
    subscriber.send(payload)
  File "/usr/local/lib/python2.7/dist-packages/ws4py/websocket.py", line 297, in send
    self._write(m)
  File "/usr/local/lib/python2.7/dist-packages/ws4py/websocket.py", line 279, in _write
    self.sock.sendall(b)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 32] Broken pipe


2018-05-02 10:41:37,526 - ERROR - emonitor.modules.alarms.faxchecker.GENERIC (regex) - field(s) empty or eval error: person,addresspart,crossing,object,alarmplan,material
2018-05-02 10:43:48,506 - ERROR - emonitor.modules.alarms.faxchecker.GENERIC (regex) - field(s) empty or eval error: person,addresspart,crossing,object,alarmplan,material


Wie kann man das Problem näher eingrenzen?



Gruß Bernd

**Comment by seiferta** [comment]
Das klingt nach einer fehlerhaften Definition der Felder.
Im Log steht "person,addresspart,crossing,object,alarmplan,material" als fehlerhaftes Feld. Es sieht also so aus, als ob die Definitionen der Felder fehlerhaft ist und aus dem Text die Werte nicht extrahiert werden können.

**Comment by bhallinger** [comment]
OK das klappt jetzt. Ich kann Einsätze erzeugen. Was jetzt noch ein Problem ist, wenn er die angegebene Strasse nicht Strassenverzeichnis findet. Wir haben im Umkreis reichlich Landes und Kreisstrassen. Müssen die alle angelegt sein? Ein Einsatz war zum beispiel L4711 a-Ort > B-Ort. 
Nachdem ich L4711 angelegt habe hat er das geschluckt. Ich bin mir aber nicht ganz sicher ob die Leistelle immer eine Strassennummer mit gibt. Vor allem wenn es z.B ein Feld- oder Waldweg ist. 
Mit anderen Worten kann ich die Auswertung so konfigurieren, dass er wenn er die Strasse findet, er die Daten nimmt, und wenn er sie nicht findet, dann halt einfach den Text der im Feld drin steht anzeigt.

Das ganze soll übrigens für Hessen angepasst werden.
